In [15]:
import numpy as np
from matplotlib import pyplot as plt

from sklearn.datasets import fetch_20newsgroups
import nltk
#nltk.download('wordnet')
#nltk.download('punkt')#, if you need "tokenizers/punkt/english.pickle", choose it
#nltk.download('averaged_perceptron_tagger')
np.random.seed(42)
import random
random.seed(42)

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

import nltk
#nltk.download()
from nltk import word_tokenize          
from nltk.stem import WordNetLemmatizer
from nltk import pos_tag



#dataset 

categories = ['comp.graphics', 'comp.os.ms-windows.misc','comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware',
'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey']
train_dataset = fetch_20newsgroups(subset = 'train', categories = categories,
 shuffle = True, random_state = None)
test_dataset = fetch_20newsgroups(subset = 'test', categories = categories,
 shuffle = True, random_state = None)

#preprocessing step

wnl = nltk.wordnet.WordNetLemmatizer()

def penn2morphy(penntag):
    """ Converts Penn Treebank tags to WordNet. """
    morphy_tag = {'NN':'n', 'JJ':'a',
                  'VB':'v', 'RB':'r'}
    try:
        return morphy_tag[penntag[:2]]
    except:
        return 'n'

def lemmatize_sent_demo(text):
    # Text input is string, returns array of lowercased strings(words).
    return [wnl.lemmatize(word.lower(), pos=penn2morphy(tag)) 
            for word, tag in pos_tag(nltk.word_tokenize(text))]
def lemmatize_sent(list_word):
    # Text input is string, returns array of lowercased strings(words).
    return [wnl.lemmatize(word.lower(), pos=penn2morphy(tag)) 
            for word, tag in pos_tag(list_word)]


#vectorize
tmp_vect = CountVectorizer(min_df=3, stop_words='english'
        ,token_pattern=r'(?u)\b[^\W\d_][^\W\d_][^\W\d_]+\b')
                           #,tokenizer=LemmaTokenizer())
X_train_tmp = tmp_vect.fit_transform(train_dataset.data)
print(X_train_tmp.shape)

print(tmp_vect.get_feature_names())

#tfidf step

tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_tmp)
print(X_train_tfidf.shape)
print('-' * 20)
print(X_train_tmp.toarray()[:30,:5])
print('-' * 20)
print(X_train_tfidf.toarray()[:30,:5])



(4732, 15674)
['aaa', 'aamir', 'aardvark', 'aargh', 'aarghhhh', 'aarhus', 'aaron', 'aau', 'abad', 'abandon', 'abate', 'abbot', 'abbott', 'abbreviation', 'abc', 'abd', 'abel', 'aber', 'aberystwyth', 'abiding', 'abilities', 'ability', 'able', 'abo', 'abominations', 'abort', 'abott', 'abs', 'absence', 'absent', 'absolute', 'absolutely', 'abstact', 'abstract', 'abstracts', 'absurd', 'absurdity', 'absurdum', 'abuse', 'abused', 'acad', 'academic', 'academy', 'acadiau', 'acbl', 'acc', 'accel', 'accelerate', 'accelerated', 'accelerating', 'acceleration', 'accelerator', 'accelerators', 'accelleration', 'accellerator', 'accented', 'accept', 'acceptable', 'acceptance', 'accepted', 'accepts', 'access', 'accessed', 'accesses', 'accessible', 'accessing', 'accessories', 'accessory', 'accident', 'accidental', 'accidentally', 'accidents', 'acclimated', 'accommodate', 'accomodate', 'accompanied', 'accomplish', 'accomplished', 'accomplishments', 'accord', 'according', 'account', 'accounted', 'accounting'

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
--------------------
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [36]:
##apply LSI block

#X_train_tfidf is the td-idf matrix
#kick imports to top later
from sklearn.decomposition import TruncatedSVD
from sklearn.decomposition import NMF

k = 50

#LSI portion
svd_info = TruncatedSVD(n_components=k)
train_lsi_matrix = svd_info.fit_transform(X_train_tfidf)
#test_lsi_matrix = svd_info.fit_transform(X_test_tfidf)

#NMF portion
nmi_info = NMF(n_components=k)
train_nmf_matrix = nmi_info.fit_transform(X_train_tfidf)
#test_nmf_matrix = nmi_info.fit_transform(X_test_tfidf)


print("Shape of LSI result: {}".format (train_lsi_matrix.shape))
print("Shape of NMF result: {}".format (train_nmf_matrix.shape))

Shape of LSI result: (4732, 50)
Shape of NMF result: (4732, 50)


In [26]:

###code cleanup in the future - saving this info
#https://stackoverflow.com/questions/15547409/how-to-get-rid-of-punctuation-using-nltk-tokenizer
words = nltk.word_tokenize(s)


import string
s = "... some string with can't  @.com 2032 punctuation ..."

words = nltk.word_tokenize(s)

words=[word.lower() for word in words if word.isalpha()]

print(words)
##loses "not" meaning from can't

['some', 'string', 'with', 'ca', 'punctuation']
