In [5]:
############# pre-setup
import numpy as np
from matplotlib import pyplot as plt

from sklearn.datasets import fetch_20newsgroups
import nltk
nltk.download('wordnet')

np.random.seed(42)
import random
random.seed(42)
##############

categories = ['comp.graphics', 'comp.os.ms-windows.misc','comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware',
'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey']
train_dataset = fetch_20newsgroups(subset = 'train', categories = categories,
 shuffle = True, random_state = None)
test_dataset = fetch_20newsgroups(subset = 'test', categories = categories,
 shuffle = True, random_state = None)


[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Ryan\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [11]:
print(type(train_dataset))
print(train_dataset.keys())
print(train_dataset.data[0])

<class 'sklearn.utils.Bunch'>
dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])
From: sac@asdi.saic.com (Steve A. Conroy x6172)
Subject: Re: Darrrrrrrrryl
Organization: SAIC
Lines: 33

In article <mssC5KCru.5Ip@netcom.com>, mss@netcom.com (Mark Singer) writes:
|> 
|> 
|> The media is beating the incident at Dodger Stadium on Wednesday to
|> death, but I haven't seen anything in rsb yet.
|> 
|> Gerald Perry of the Cardinals pinch hit in the eighth inning with two
|> on and his club down by a run.  He stroked a line drive into the
|> right field corner.  The ball cleared the three-foot high fence and
|> went into the crowd.  Darryl, racing over from right center, got to
|> the spot in time to reach his glove up over the short fence, but he
|> missed the ball.  A fan sitting in the front row, wearing a mitt,
|> reached up and caught the ball.  Home run.
|> 
|> Now I've seen the replay several times and I have concluded that
|> Darryl missed the ball, and that the fan's g

In [34]:

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

#exclude numbers using regex
#r'\b[^\d\W]+\b gets rid of numbers but not weird text like '___' '_j'
#r'(?ui)\b\w*[a-z]+\w*\b' gets rid of weird text but not all numbers
tmp_vect = CountVectorizer(min_df=3, stop_words='english'
                             ,token_pattern=r'(?ui)\b\w*[a-z]+\w*\b')
print(tmp_vect)

#transform dataset into a matrix using fit_transform.
X_train_tmp = tmp_vect.fit_transform(train_dataset.data)
print(X_train_tmp.shape)

#check output
#print(tmp_vect.get_feature_names())

#tdif step
tfidf_transformer = TfidfTransformer()

X_train_tfidf = tfidf_transformer.fit_transform(X_train_tmp)
print(X_train_tfidf.shape)
print('-' * 20)
print(X_train_tmp.toarray()[:30,:5])
print('-' * 20)
print(X_train_tfidf.toarray()[:30,:5])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=3,
                ngram_range=(1, 1), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?ui)\\b\\w*[a-z]+\\w*\\b',
                tokenizer=None, vocabulary=None)
(4732, 18754)
(4732, 18754)
--------------------
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
--------------------
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0

318


In [ ]:
##lemmatization to occur later